### PR TITLE
[FR-192] NextJS Single Channel Login Functionality

### PR DESCRIPTION
**Pull request by tylergeorges**
Replaces logout button with login button and vice versa depending on user's auth status

### CODE REVIEW

**Review by Yomanz — APPROVED** [review]
Looks good!

**Review by advaith1 — CHANGES_REQUESTED** [review]
the threads button is rounded on this branch, cutting off the icon
image

**Comment by advaith1** [comment]
actually nvm that is an issue with the single-channel PR - why is this a separate PR? this is necessary functionality for single-channel mode, it should be merged into that PR

**Comment by advaith1** [comment]
why's GitHub failing to display the login icon? https://github.com/widgetbot-io/embed/blob/3411afe6997d796384206606bedac716da76306f/src/res/images/discordAssets/button-icons/icon-login.svg

**Comment by tylergeorges** [comment]
> why's GitHub failing to display the login icon? https://github.com/widgetbot-io/embed/blob/3411afe6997d796384206606bedac716da76306f/src/res/images/discordAssets/button-icons/icon-login.svg

Fixed

**Review by advaith1 — APPROVED** [review]

**Pull request merged**
